MOD_UFASTLZ_DIR := $(USERMOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_UFASTLZ
CFLAGS_USERMOD += -I$(MOD_UFASTLZ_DIR)
CFLAGS_USERMOD += -I$(MOD_UFASTLZ_DIR)/FastLZ/

SRC_USERMOD += $(MOD_UFASTLZ_DIR)/FastLZ/fastlz.c
SRC_USERMOD += $(MOD_UFASTLZ_DIR)/modufastlz.c
